Test for 7-base_geometry.py
-------------------------------------------

Test 0: importing module
>>> BG = __import__('7-base_geometry').BaseGeometry
>>>
-------------------------------------------

Test 1: Print Object Area

>>> bg = BG()
>>> bg.area()
Traceback (most recent call last):
...
Exception: area() is not implemented
>>>

-------------------------------------------
Checking integer_validator Method
-------------------------------------------

Test 2: Value is not integer 

>>> bg.integer_validator("my int" , "ALX")
Traceback (most recent call last):
...
TypeError: my int must be an integer
>>>

-------------------------------------------

Test 3: Value is equal or less than 0

>>> bg.integer_validator("my int" , -99)
Traceback (most recent call last):
...
ValueError: my int must be greater than 0
>>>

-------------------------------------------

Test 4: Passing a positive value

>>> bg.integer_validator("name", 5)

-------------------------------------------

Test 5: Integer_validator with no arguments

>>> bg.integer_validator("name", 5)

>>> bg.integer_validator()
Traceback (most recent call last):
...
TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
>>>

-------------------------------------------

Test 6: Passing one argument to area method

>>> bg.area(5)
Traceback (most recent call last):
...
TypeError: area() takes 1 positional argument but 2 were given
>>>

-------------------------------------------

Test 7: Passing one argument to integer_validator
>>> bg.integer_validator("name")
Traceback (most recent call last):
...
TypeError: integer_validator() missing 1 required positional argument: 'value'

-------------------------------------------

Test 8: Passing two argument to area method

>>> bg.area(5,9)
Traceback (most recent call last):
...
TypeError: area() takes 1 positional argument but 3 were given
>>>

-------------------------------------------

Test 9: Passing Three argument to integer_validator
>>> bg.integer_validator("name",1,8)
Traceback (most recent call last):
...
TypeError: integer_validator() takes 3 positional arguments but 4 were given

